### ISSUE TITLE
Case 3 adds diamond and hangs browser

### ISSUE THREAD

**Issue by TejasQ** [Contiamo/contiamo-ui-components#208]
@micha-f reported this initially and could help reproduce this bug. This bug _only occurs sometimes_.

## Description
Case 3 adds a diamond instead of a rotated square node and hangs the browser on completion

![image](https://user-images.githubusercontent.com/9947422/32103570-45cdf8b0-bb21-11e7-84ae-f4c73e39c2c3.png)

**Comment by ImogenF** [comment]
This is fixed now. The diamonds are intentional - testing node accessors. The dashed lines no longer cause a problem.
