### ISSUE TITLE
Currently impossible to get started coding

### ISSUE THREAD

**Issue by TejasQ** [Contiamo/contiamo-ui-components#225]
## Steps to Reproduce
- `git clone git@github.com:Contiamo/contiamo-ui-components.git`
- `cd contiamo-ui-components`
- `yarn install`
- `yarn bootstrap`
- `cd packages/showcase`
- `yarn start`
- death. ☠️

I just want to edit a component. 😢

## Screenshot
![image](https://user-images.githubusercontent.com/9947422/32615071-023a0f64-c56f-11e7-93bc-9e1d50100f86.png)

**Comment by peterszerzo** [comment]
Thanks for reporting, @TejasQ, I'll sort this out in an expedited fashion.
