### ISSUE TITLE
Export `contiamoTheme` from `contiamo-ui-components`

### ISSUE THREAD

**Issue by TejasQ** [Contiamo/contiamo-ui-components#229]
## Problem
One cannot use `contiamo-ui-components` without a theme, which was factored out recently to live in `contiamo-ui-theme`. 

So, `yarn add contiamo-ui-components` would not be sufficient to get up and running with this project. Instead, one would have to:

`yarn add contiamo-ui-components contiamo-ui-theme`

```jsx
import { Card, ThemeProvider } from "contiamo-ui-components" 
import { contiamoTheme } from "contiamo-ui-theme"

export default () => <ThemeProvider theme={contiamoTheme}>
  <Card>HELLO</Card>
</ThemeProvider>
```

Having to import and `yarn add` two dependencies for two dependent parts seems counter-intuitive, given that `ui-components` is unusable without `ui-theme`.

## Proposed Solution
Include `contiamoTheme` in the exports of `contiamo-ui-components` to allow for an API as so:

```jsx
import { Card, ThemeProvider, contiamoTheme } from "contiamo-ui-theme"

export default () => <ThemeProvider theme={contiamoTheme}>
  <Card>HELLO</Card>
</ThemeProvider>
```

Given this solution, the `index.js` of `contiamo-ui-components` would simply:
`export { contiamoTheme } from "contiamo-ui-theme"`

and that would be that.

## Devil's Advocate 😈
One could argue that React handles things the way they are currently, forcing two dependencies: `react` and `react-dom`: React will not work without ReactDOM. Therefore, this is very much up for discussion. The obvious counter-point here is that ReactDOM is included only once, at root level to render the initial component and not its constituent parts, whereas `contiamoTheme` could be used in multiple locations, causing inconvenient multiple imports.

Thoughts?

**Comment by peterszerzo** [comment]
I would argue `contiamoTheme` shouldn't be used in multiple locations in an application. Import it once in the top-level component where `ThemeProvider` is being introduced, and access its value when writing glamorous components. The story is quite different for the `Theme` type definition, which I think we should export in addition to `contiamoTheme`.

**Comment by peterszerzo** [comment]
Closing this since it's been merged. Release coming up within the hour.
