### ISSUE TITLE
<Upload /> requires an action in typedef

### ISSUE THREAD

**Issue by TejasQ** [Contiamo/contiamo-ui-components#232]
`<Upload />` requires an action in typedef _even if_ the `request` prop is specified. Can we make the `action` prop optional?

**Comment by TejasQ** [comment]
Additionally, would be nice if `request` was `Promise<any>` as opposed to `any`

**Comment by peterszerzo** [comment]
Looks like this is already implemented in master - please feel free to re-open if you find further rooms for improvement around `Upload` type definitions.
